### ISSUE TITLE
Camera System

### ISSUE THREAD

**Issue by heed13** [heed13/CS-3540-Borderlands#3]
Does each player follow themselves or do we fit each player on the same camera?

**Comment by baston85** [comment]
I kind of like the idea of putting everyone under the same camera and requiring them to travel together, but sometimes that gets annoying when you have to wait for someone before you can move, or you get trapped behind a wall when the end goes outside the camera view. I think it would be easier to implement a camera for each player and allow them to move independently, but for single-camera, I think I already know of an easy way to keep players from leaving the viewable screen area, and have some ideas for getting the camera to track the group correctly.

If neither of you have strong opinions on which way to go, I think a good deciding factor could be the portion of the screen each character takes up. If it's a larger portion, then a separate camera would probably be better (I'm picturing Gun Bros scale but on full size screen http://goo.gl/wCRm6O). If characters end up being tiny compared to the total screen size, a single camera might be better. (good scale example is Hammerwatch https://goo.gl/lQPcZM)

**Comment by heed13** [comment]
closing issue, i put this up on the google doc because its more of a design question
